export const COLORS = {
  primary: "#FFD700",
  secondary: "#1a1a1a",
  background: "#1a1a1a",
  card: "#2a2a2a",
  text: "#FFFFFF",
  textSecondary: "#CCCCCC",
};

export const SLOT_MACHINES = [
  { id: 1, name: "Frutas Clásicas", icon: "🍒", theme: "clásico" },
  { id: 2, name: "Diamantes Brillantes", icon: "💎", theme: "lujo" },
  { id: 3, name: "Tesoro Egipcio", icon: "🐪", theme: "aventura" },
  { id: 4, name: "Fiesta Mexicana", icon: "🎉", theme: "fiesta" },
  { id: 5, name: "Galaxia Estelar", icon: "🌌", theme: "espacio" },
];

export const GAMES_LIST = [
  { id: 1, name: "Blackjack", icon: "♠️", category: "Cartas" },
  { id: 2, name: "Póker Texas", icon: "🎴", category: "Cartas" },
  { id: 3, name: "Baccarat", icon: "🃏", category: "Cartas" },
  { id: 4, name: "Póker Caribbean", icon: "🌴", category: "Cartas" },
  { id: 5, name: "Three Card", icon: "3️⃣", category: "Cartas" },
  { id: 6, name: "Ruleta Europea", icon: "🎡", category: "Ruleta" },
  { id: 7, name: "Ruleta Americana", icon: "🇺🇸", category: "Ruleta" },
  { id: 8, name: "Ruleta Francesa", icon: "🇫🇷", category: "Ruleta" },
  { id: 9, name: "Craps", icon: "🎲", category: "Dados" },
  { id: 10, name: "Sic Bo", icon: "🎯", category: "Dados" },
  { id: 11, name: "Bingo", icon: "🅱️", category: "Lotería" },
  { id: 12, name: "Keno", icon: "🔢", category: "Lotería" },
  { id: 13, name: "Jacks or Better", icon: "J️⃣", category: "Video Poker" },
  { id: 14, name: "Deuces Wild", icon: "2️⃣", category: "Video Poker" },
  { id: 15, name: "Joker Poker", icon: "🃏", category: "Video Poker" },
  { id: 16, name: "Pai Gow", icon: "🎎", category: "Especiales" },
  { id: 17, name: "Red Dog", icon: "🐕", category: "Especiales" },
  { id: 18, name: "War", icon: "⚔️", category: "Especiales" },
  { id: 19, name: "Punto Banco", icon: "🎯", category: "Mesas" },
  { id: 20, name: "Let It Ride", icon: "🎠", category: "Mesas" },
  { id: 21, name: "Dragon Tiger", icon: "🐉", category: "Rápidos" },
  { id: 22, name: "Casino War", icon: "🎖️", category: "Rápidos" },
  { id: 23, name: "Virtual Blackjack", icon: "♣️", category: "Virtuales" },
  { id: 24, name: "Virtual Roulette", icon: "⚫", category: "Virtuales" },
  { id: 25, name: "Virtual Baccarat", icon: "💎", category: "Virtuales" },
  { id: 26, name: "Sports Betting", icon: "🏈", category: "Deportes" },
  { id: 27, name: "Wheel of Fortune", icon: "🎡", category: "Otros" },
  { id: 28, name: "Big Six Wheel", icon: "⚙️", category: "Otros" },
  { id: 29, name: "Pachinko", icon: "🎰", category: "Otros" },
  { id: 30, name: "Banca Francesa", icon: "🇫🇷", category: "Otros" },
];